### ISSUE TITLE
Poder borrar canciones desde /canciones-pedidas

### ISSUE THREAD

**Issue by goltra** [goltra/goltrakaraoke#2]
Actualmente cuando vas a la ruta /canciones-pedidas se muestras un listado con las canciones que hay en cola y su respectivo cantante. 
La idea es implementar una funcionalidad que permita borrar una canción con el fin de solventar solicitudes duplicadas.

**Comment by JoseJavega** [comment]
Añadido un botón al div de las canciones para poder borrarlas
Creado en router.js un nuevo end point /delsong
Creada en canciones-pedidas.html el script para eliminar la canción llamando al endpoint /delsong
